Web/Controllers/CategoryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.ExceptionFilter.Exceptions;
using Web.Models;
using Web.Models.DTO;
using Web.Services.Interfaces;

namespace Web.Controllers
{
    public class CategoryController : Controller
    {
        public readonly ICategoryService categoryService;
        public readonly IProductService productService;
        private readonly IMapper mapper;

        public CategoryController(ICategoryService _categoryService, IProductService _productService, IMapper _mapper)
        {
            categoryService = _categoryService;
            productService = _productService;
            mapper = _mapper;   
        }
        public async Task<IActionResult> Index(string? SearchString)
        {
            var categorys = await categoryService.GetAllDetailsAsync(SearchString, GetToken());

            return View(categorys);
        }
        public async Task<IActionResult> Details(int id)
        {
            var category = await categoryService.GetByIdAsync(id, GetToken());

            return View(category);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Create()
        {
            await UpdataProductViewBag();

            return View();
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryCreateDTO category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await categoryService.AddAsync(category, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataProductViewBag();

            return View(category);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Edit(int id)
        {
            await UpdataProductViewBag();

            var category = mapper.Map<CategoryUpdateDTO>(await categoryService.GetByIdAsync(id, GetToken()));

            return View(category);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CategoryUpdateDTO category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await categoryService.UpdateAsync(category.Id, category, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataProductViewBag();

            return View(category);

        }
        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await categoryService.GetByIdAsync(id, GetToken());

            return View(category);
        }
        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await categoryService.DeleteAsync(id, GetToken());

            return RedirectToAction("Index");
        }

        #region PrivateMethods
        private string GetToken()
        {
            return HttpContext.Session.GetString(SD.SessionToken);
        }

        private async Task UpdataProductViewBag()
        {
            var products = await productService.GetAllAsync(GetToken());

            ViewBag.Products = new SelectList(products, "Id", "Name");
        }
        #endregion
    }
}

Web/Controllers/GameController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.ExceptionFilter.Exceptions;
using Web.Models;
using Web.Models.DTO;
using Web.Services.Interfaces;

namespace Web.Controllers
{
    public class GameController : Controller
    {
        public readonly IProductService productService;
        public readonly IProducerService producerService;
        public readonly ICategoryService categoryService;
        private readonly IMapper mapper;

        public GameController(IProductService _productService, IProducerService _producerService, ICategoryService _categoryService, IMapper _mapper)
        {
            productService = _productService;
            producerService = _producerService;
            categoryService = _categoryService;
            mapper = _mapper;
        }
        public async Task<IActionResult> Index(string? SearchString)
        {

            var products = await productService.GetAllDetailsAsync(SearchString, GetToken());

            return View(products);
        }

        public async Task<IActionResult> Details(int id)
        {
            var product = await productService.GetByIdAsync(id, GetToken());

            return View(product);
        }       

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Create()
        {
            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View();
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductCreateDTO product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await productService.AddAsync(product, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View(product);         
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Edit(int id)
        {
            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            var product = mapper.Map<ProductUpdateDTO>( await productService.GetByIdAsync(id, GetToken()));

            
            return View(product);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductUpdateDTO product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await productService.UpdateAsync(product.Id, product, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View(product); 
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await productService.GetByIdAsync(id,GetToken());

            return View(product);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await productService.DeleteAsync(id,GetToken());

            return RedirectToAction("Index");
        }

        #region PrivateMethods
        private string GetToken()
        {
            return HttpContext.Session.GetString(SD.SessionToken)!;
        }

        private async Task UpdataCategoryViewBag()
        {
            var categorys = await categoryService.GetAllAsync(GetToken());

            ViewBag.Categoryes = new SelectList(categorys, "Id", "Name");
        }

        private async Task UpdataProducerViewBag()
        {
            var producers = await producerService.GetAllAsync(GetToken());

            ViewBag.Producers = new SelectList(producers, "Id", "Name");
        }
        #endregion
    }
}

Web/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.ExceptionFilter.Exceptions;
using Web.Models;
using Web.Models.DTO;
using Web.Services;
using Web.Services.Interfaces;

namespace Web.Controllers
{
    public class ProductController : Controller
    {
        public readonly IProductService productService;
        public readonly IProducerService producerService;
        public readonly ICategoryService categoryService;
        private readonly IMapper mapper;

        public ProductController(IProductService _productService, IProducerService _producerService, ICategoryService _categoryService, IMapper _mapper)
        {
            productService = _productService;
            producerService = _producerService;
            categoryService = _categoryService;
            mapper = _mapper;
        }
        public async Task<IActionResult> Index()
        {
            await UpdataCategoryViewBag();

            var products = await productService.GetAllDetailsAsync(GetToken());

            return View(products);
        }

        //public async Task<IActionResult> Filter(int catgeoryId, string SearchString)
        //{
        //    await UpdataCategoryViewBag();

        //    var products = await productService.GetAllAsync(GetToken());

        //    return View(products); 
        //}

        public async Task<IActionResult> Details(int id)
        {
            var product = await productService.GetByIdAsync(id, GetToken());

            return View(product);
        }       

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Create()
        {
            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View();
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductCreateDTO product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await productService.AddAsync(product, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View(product);         
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Edit(int id)
        {
            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            var product = mapper.Map<ProductUpdateDTO>( await productService.GetByIdAsync(id, GetToken()));

            
            return View(product);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductUpdateDTO product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await productService.UpdateAsync(product.Id, product, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View(product); 
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await productService.GetByIdAsync(id,GetToken());

            return View(product);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await productService.DeleteAsync(id,GetToken());

            return RedirectToAction("Index");
        }

        #region PrivateMethods
        private string GetToken()
        {
            return HttpContext.Session.GetString(SD.SessionToken);
        }

        private async Task UpdataCategoryViewBag()
        {
            var categorys = await categoryService.GetAllAsync(GetToken());

            ViewBag.Categoryes = new SelectList(categorys, "Id", "Name");
        }

        private async Task UpdataProducerViewBag()
        {
            var producers = await producerService.GetAllAsync(GetToken());

            ViewBag.Producers = new SelectList(producers, "Id", "Name");
        }
        #endregion
    }
}

Web/Views/Category/Create.cshtml
@model CategoryCreateDTO

@{
    ViewData["Title"] = "Create a new Category";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new Category</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProductsId" class="control-label"></label>
                                <select asp-for="ProductsId" class="form-control" asp-items="ViewBag.Products" multiple></select>
                                <span asp-validation-for="ProductsId" class="text-danger"></span>
                            </div>

                        </div>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

Web/Views/Category/Delete.cshtml
@model CategoryDTO

@{
    ViewData["Title"] = "Delete Category";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete confirmation for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                    </form>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Views/Category/Details.cshtml
@model CategoryDTO

@{
    ViewData["Title"] = "List of Categorys";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>Games</th>
                </tr>
            </thead>
            <tbody>
                <tr class="text-center">
                    <td class="align-middle">
                        @Html.DisplayFor(model => model.Name)
                    </td>
                    <td>
                        @if (Model.Products != null)
                        {
                            <div class="row">
                                @foreach (var product in Model.Products)
                                {
                                    <div class="col-md-4">
                                        <img class="border-info rounded-circle" src="@product.Image" style="max-width: 100px" />
                                        <br />
                                        <a asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">@product.Name</a>
                                    </div>
                                }
                            </div>
                        }
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

Web/Views/Category/Edit.cshtml
@model CategoryUpdateDTO


@{
    ViewData["Title"] = "Update Category";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update Game</h4>
        </p>

       <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit" asp-route-id="@Model.Id">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                             <div class="form-group">
                                <label asp-for="ProductsId" class="control-label"></label>
                                <select asp-for="ProductsId" class="form-control" asp-items="ViewBag.Products" multiple></select>
                                <span asp-validation-for="ProductsId" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

Web/Views/Category/Index.cshtml
@model IEnumerable<CategoryDTO>

@{
    ViewData["Title"] = "List of Categorys";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>Games</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @if (item.Products != null)
                            {
                                <div class="row">
                                    @foreach (var product in item.Products)
                                    {
                                        <div class="col-md-4">
                                            <img class="border-info rounded-circle" src="@product.Image" style="max-width: 100px" />
                                            <br />
                                            <a asp-controller="Game" asp-action="Details" asp-route-id="@product.Id">@product.Name</a>
                                        </div>
                                    }
                                </div>
                            }
                        </td>
                        <td class="align-middle">
                            <div class="btn-group">
                                <a class="btn btn-outline-primary btn-sm" asp-action="Edit" asp-route-id="@item.Id style="margin-right: 10px;"><i class="bi bi-pencil-square"></i>Edit</a>
                                <a class="btn btn-danger btn-sm text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@await Html.PartialAsync("_CreateItem", "Category") 