Web/Controllers/CategoryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.ExceptionFilter.Exceptions;
using Web.Models;
using Web.Models.DTO;
using Web.Services.Interfaces;

namespace Web.Controllers
{
    public class CategoryController : Controller
    {
        public readonly ICategoryService categoryService;
        public readonly IProductService productService;
        private readonly IMapper mapper;

        public CategoryController(ICategoryService _categoryService, IProductService _productService, IMapper _mapper)
        {
            categoryService = _categoryService;
            productService = _productService;
            mapper = _mapper;   
        }
        public async Task<IActionResult> Index(string? SearchString)
        {
            var categorys = await categoryService.GetAllDetailsAsync(SearchString, GetToken());

            return View(categorys);
        }
        public async Task<IActionResult> Details(int id)
        {
            var category = await categoryService.GetByIdAsync(id, GetToken());

            return View(category);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Create()
        {
            await UpdataProductViewBag();

            return View();
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryCreateDTO category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await categoryService.AddAsync(category, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataProductViewBag();

            return View(category);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Edit(int id)
        {
            await UpdataProductViewBag();

            var category = mapper.Map<CategoryUpdateDTO>(await categoryService.GetByIdAsync(id, GetToken()));

            return View(category);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CategoryUpdateDTO category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await categoryService.UpdateAsync(category.Id, category, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataProductViewBag();

            return View(category);

        }
        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await categoryService.GetByIdAsync(id, GetToken());

            return View(category);
        }
        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await categoryService.DeleteAsync(id, GetToken());

            return RedirectToAction("Index");
        }

        #region PrivateMethods
        private string GetToken()
        {
            return HttpContext.Session.GetString(SD.SessionToken);
        }

        private async Task UpdataProductViewBag()
        {
            var products = await productService.GetAllAsync(GetToken());

            ViewBag.Products = new SelectList(products, "Id", "Name");
        }
        #endregion
    }
}

Web/Controllers/GameController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.ExceptionFilter.Exceptions;
using Web.Models;
using Web.Models.DTO;
using Web.Services.Interfaces;

namespace Web.Controllers
{
    public class GameController : Controller
    {
        public readonly IProductService productService;
        public readonly IProducerService producerService;
        public readonly ICategoryService categoryService;
        private readonly IMapper mapper;

        public GameController(IProductService _productService, IProducerService _producerService, ICategoryService _categoryService, IMapper _mapper)
        {
            productService = _productService;
            producerService = _producerService;
            categoryService = _categoryService;
            mapper = _mapper;
        }
        public async Task<IActionResult> Index(string? SearchString)
        {

            var products = await productService.GetAllDetailsAsync(SearchString, GetToken());

            return View(products);
        }

        public async Task<IActionResult> Details(int id)
        {
            var product = await productService.GetByIdAsync(id, GetToken());

            return View(product);
        }       

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Create()
        {
            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View();
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductCreateDTO product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await productService.AddAsync(product, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View(product);         
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Edit(int id)
        {
            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            var product = mapper.Map<ProductUpdateDTO>( await productService.GetByIdAsync(id, GetToken()));

            
            return View(product);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductUpdateDTO product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await productService.UpdateAsync(product.Id, product, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View(product); 
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await productService.GetByIdAsync(id,GetToken());

            return View(product);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await productService.DeleteAsync(id,GetToken());

            return RedirectToAction("Index");
        }

        #region PrivateMethods
        private string GetToken()
        {
            return HttpContext.Session.GetString(SD.SessionToken)!;
        }

        private async Task UpdataCategoryViewBag()
        {
            var categorys = await categoryService.GetAllAsync(GetToken());

            ViewBag.Categoryes = new SelectList(categorys, "Id", "Name");
        }

        private async Task UpdataProducerViewBag()
        {
            var producers = await producerService.GetAllAsync(GetToken());

            ViewBag.Producers = new SelectList(producers, "Id", "Name");
        }
        #endregion
    }
}

Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;
using Web.Models;
using Web.Models.DTO.OrderDTO;
using Web.Services.Interfaces;

namespace Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService orderService;
        public OrderController(IOrderService _orderService)
        {
            orderService = _orderService;
        }

        [Authorize]
        public async Task<IActionResult> Index(string? SearchString)
        {
            var userRole = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;
            List<OrderDTO> orders;

            if (userRole == "admin" || userRole == "employee")
            {
                orders = await orderService.GetAllOrder(SearchString, GetToken());
            }
            else
            {
                var userEmail = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
                orders = await orderService.GetUserOrder(userEmail, GetToken()); /// addd SearchString
            }

            return View(orders);
        }
        private string GetToken()
        {
            return HttpContext.Session.GetString(SD.SessionToken);
        }
    }
}

Web/Controllers/ProducerController.cs
using Microsoft.AspNetCore.Mvc;
using Web.Models.DTO;
using Web.Models;
using Web.Services.Interfaces;
using Microsoft.AspNetCore.Mvc.Rendering;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Web.ExceptionFilter.Exceptions;

namespace Web.Controllers
{
    public class ProducerController : Controller
    {
        public readonly IProducerService producerService;
        public readonly IProductService productService;
        private readonly IMapper mapper;

        public ProducerController(IProducerService _producerService, IProductService _productService, IMapper _mapper)
        {
            producerService = _producerService;
            productService = _productService;
            mapper = _mapper;
        }
        public async Task<IActionResult> Index(string? SearchString)
        {
            var Producers = await producerService.GetAllDetailsAsync(SearchString, GetToken());

            return View(Producers);
        }

        public async Task<IActionResult> Details(int id)
        {
            var producer = await producerService.GetByIdAsync(id, GetToken());

            return View(producer);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Create()
        {
            await UpdataProductViewBag();

            return View();
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProducerCreateDTO producer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await producerService.AddAsync(producer, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataProductViewBag(); ;

            return View(producer);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Edit(int id)
        {
            await UpdataProductViewBag();

            var Producer = mapper.Map<ProducerUpdateDTO>(await producerService.GetByIdAsync(id, GetToken()));

            return View(Producer);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProducerUpdateDTO producer)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await producerService.UpdateAsync(producer.Id, producer, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataProductViewBag();

            return View(producer);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Delete(int id)
        {
            var producer=  await producerService.GetByIdAsync(id, GetToken());

            return View(producer);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await producerService.DeleteAsync(id, GetToken());

            return RedirectToAction("Index");
        }

        #region PrivateMethods
        private string GetToken()
        {
            return HttpContext.Session.GetString(SD.SessionToken);
        }

        private async Task UpdataProductViewBag()
        {
            var products = await productService.GetAllAsync(GetToken());

            ViewBag.Products = new SelectList(products, "Id", "Name");
        }
        #endregion
    }
}

Web/Views/Game/Create.cshtml
@model ProductCreateDTO

@{
    ViewData["Title"] = "Create a new Game";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new Game</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImagePreview" />
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Image" class="control-label"></label>
                                <input asp-for="Image" class="form-control" />
                                <span asp-validation-for="Image" class="text-danger"></span>
                            </div>
                           <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CategoriesId" class="control-label"></label>
                                <select asp-for="CategoriesId" class="form-control" asp-items="ViewBag.Categoryes" multiple></select>
                                <span asp-validation-for="CategoriesId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById("ImagePreview");
            output.src = $("#Image").val();
        });
        $("#Image").on("change", function () {
            var output = document.getElementById("ImagePreview");
            output.src = $(this).val();
        })
    </script>
}

Web/Views/Game/Delete.cshtml
@model ProductDTO

@{
    ViewData["Title"] = "Delete Game";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete confirmation for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="max-width: 150px" id="PicturePreview" />
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input asp-for="Image" class="form-control" readonly />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" readonly />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" readonly />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                    </form>
                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('PicturePreview');
            output.src = $("#Image").val();
        })
    </script>
}

Web/Views/Game/Details.cshtml
@model ProductDTO

@{
    ViewData["Title"] = "Game details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.Image" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text"><b>Description: </b>@Model.Description</p>
                        @if(Model.Price == 0)
                        {
                            <p class="card-text"><b>Price: </b>Free</p>
                        }
                        else
                        {
                            <p class="card-text"><b>Price: </b>@Model.Price$</p>
                        }
                            
                        <p class="card-text">
                            <b>Producer: </b>                            
                            <a asp-controller="Producer" asp-action="Details" asp-route-id="@Model.Producer.Id">
                                <img class="border-info rounded-circle" src="@Model.Producer.Logo" style="max-width: 150px" /></a>
                            <text>&nbsp;</text>
                            <a asp-controller="Producer" asp-action="Details" asp-route-id="@Model.Producer.Id">  @Model.Producer.Name</a>
                        </p>
                        <p class="card-text">
                            <b>Category: </b>
                                @foreach (var item in Model.Categories)
                                {
                                    <a asp-controller="Category" asp-action="Details" asp-route-id="@item.Id">@item.Name </a>
                                    <text>&nbsp;</text>
                                }
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                            <a class="btn btn-success text-white"
                               asp-controller="Orders"
                               asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Views/Game/Edit.cshtml
@model ProductUpdateDTO


@{
    ViewData["Title"] = "Update Game";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update Game</h4>
        </p>

       <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit" asp-route-id="@Model.Id">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    
                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImagePreview" />
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Image" class="control-label"></label>
                                <input asp-for="Image" class="form-control" />
                                <span asp-validation-for="Image" class="text-danger"></span>
                            </div>
                           <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CategoriesId" class="control-label"></label>
                                <select asp-for="CategoriesId" class="form-control" asp-items="ViewBag.Categoryes" multiple></select>
                                <span asp-validation-for="CategoriesId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById("ImagePreview");
            output.src = $("#Image").val();
        });
        $("#Image").on("change", function () {
            var output = document.getElementById("ImagePreview");
            output.src = $(this).val();
        })
    </script>
}

Web/Views/Game/Index.cshtml
@model IEnumerable<ProductDTO>
@{
    ViewData["Title"] = "List of Games";
}

<br />
<div class="row">
    @if(Model == null)
    {
        <b>Welcome</b>
    }
    else
    {
        @foreach (var item in Model)
        {
            <div class="col-md-4 col-xs-6 border-primary mb-3">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-header text-white bg-info">
                                <p class="card-text">
                                    <h5 class="card-title">
                                        @item.Name
                                        @if (User.IsInRole("admin") || User.IsInRole("employee"))
                                        {
                                            <a class="text-white float-right" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i></a>
                                            <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square mr-3 "></i></a>
                                        }
                                    </h5>
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <img src="@item.Image" width="100%" alt="@item.Name">
                        </div>
                        <div class="col-md-6">
                            <div class="card-body">
                                <p class="card-text"><b>Decription: </b>@item.Description</p>
                                @if (item.Price == 0)
                                {
                                    <p class="card-text"><b>Price: </b>Free</p>
                                }
                                else
                                {
                                    <p class="card-text"><b>Price: </b>@item.Price$</p>
                                }
                                <p class="card-text">
                                    <b>category: </b>
                                    @foreach (var category in item.Categories)
                                    {
                                        <a asp-controller="Category" asp-action="Details" asp-route-id="@category.Id">@category.Name </a>
                                        <text>&nbsp;</text>
                                    }
                                </p>

                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="card-footer ">
                                <p class="card-text">
                                    <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                        <i class="bi bi-eye-fill"></i> Show Details
                                    </a>
                                    <a class="btn btn-success text-white"
                                        asp-controller="Order"
                                        asp-action="AddItemToShoppingCart"
                                        asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
    
</div>

@await Html.PartialAsync("_CreateItem", "Game")