Web/Controllers/CategoryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.ExceptionFilter.Exceptions;
using Web.Models;
using Web.Models.DTO;
using Web.Services.Interfaces;

namespace Web.Controllers
{
    public class CategoryController : Controller
    {
        public readonly ICategoryService categoryService;
        public readonly IProductService productService;
        private readonly IMapper mapper;

        public CategoryController(ICategoryService _categoryService, IProductService _productService, IMapper _mapper)
        {
            categoryService = _categoryService;
            productService = _productService;
            mapper = _mapper;   
        }
        public async Task<IActionResult> Index(string? SearchString)
        {
            var categorys = await categoryService.GetAllDetailsAsync(SearchString, GetToken());

            return View(categorys);
        }
        public async Task<IActionResult> Details(int id)
        {
            var category = await categoryService.GetByIdAsync(id, GetToken());

            return View(category);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Create()
        {
            await UpdataProductViewBag();

            return View();
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryCreateDTO category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await categoryService.AddAsync(category, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataProductViewBag();

            return View(category);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Edit(int id)
        {
            await UpdataProductViewBag();

            var category = mapper.Map<CategoryUpdateDTO>(await categoryService.GetByIdAsync(id, GetToken()));

            return View(category);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CategoryUpdateDTO category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await categoryService.UpdateAsync(category.Id, category, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataProductViewBag();

            return View(category);

        }
        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await categoryService.GetByIdAsync(id, GetToken());

            return View(category);
        }
        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await categoryService.DeleteAsync(id, GetToken());

            return RedirectToAction("Index");
        }

        #region PrivateMethods
        private string GetToken()
        {
            return HttpContext.Session.GetString(SD.SessionToken);
        }

        private async Task UpdataProductViewBag()
        {
            var products = await productService.GetAllAsync(GetToken());

            ViewBag.Products = new SelectList(products, "Id", "Name");
        }
        #endregion
    }
}

Web/Controllers/GameController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.ExceptionFilter.Exceptions;
using Web.Models;
using Web.Models.DTO;
using Web.Services.Interfaces;

namespace Web.Controllers
{
    public class GameController : Controller
    {
        public readonly IProductService productService;
        public readonly IProducerService producerService;
        public readonly ICategoryService categoryService;
        private readonly IMapper mapper;

        public GameController(IProductService _productService, IProducerService _producerService, ICategoryService _categoryService, IMapper _mapper)
        {
            productService = _productService;
            producerService = _producerService;
            categoryService = _categoryService;
            mapper = _mapper;
        }
        public async Task<IActionResult> Index(string? SearchString)
        {

            var products = await productService.GetAllDetailsAsync(SearchString, GetToken());

            return View(products);
        }

        public async Task<IActionResult> Details(int id)
        {
            var product = await productService.GetByIdAsync(id, GetToken());

            return View(product);
        }       

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Create()
        {
            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View();
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductCreateDTO product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await productService.AddAsync(product, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View(product);         
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Edit(int id)
        {
            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            var product = mapper.Map<ProductUpdateDTO>( await productService.GetByIdAsync(id, GetToken()));

            
            return View(product);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductUpdateDTO product)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await productService.UpdateAsync(product.Id, product, GetToken());

                    return RedirectToAction("Index");
                }
                catch (BadRequestException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            await UpdataCategoryViewBag();
            await UpdataProducerViewBag();

            return View(product); 
        }

        [Authorize(Policy = "AdminOrEmployee")]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await productService.GetByIdAsync(id,GetToken());

            return View(product);
        }

        [Authorize(Policy = "AdminOrEmployee")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await productService.DeleteAsync(id,GetToken());

            return RedirectToAction("Index");
        }

        #region PrivateMethods
        private string GetToken()
        {
            return HttpContext.Session.GetString(SD.SessionToken)!;
        }

        private async Task UpdataCategoryViewBag()
        {
            var categorys = await categoryService.GetAllAsync(GetToken());

            ViewBag.Categoryes = new SelectList(categorys, "Id", "Name");
        }

        private async Task UpdataProducerViewBag()
        {
            var producers = await producerService.GetAllAsync(GetToken());

            ViewBag.Producers = new SelectList(producers, "Id", "Name");
        }
        #endregion
    }
}

Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;
using Web.Models;
using Web.Models.DTO.OrderDTO;
using Web.Services.Interfaces;

namespace Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService orderService;
        public OrderController(IOrderService _orderService)
        {
            orderService = _orderService;
        }

        [Authorize]
        public async Task<IActionResult> Index(string? SearchString)
        {
            var userRole = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Role)?.Value;
            List<OrderDTO> orders;

            if (userRole == "admin" || userRole == "employee")
            {
                orders = await orderService.GetAllOrder(SearchString, GetToken());
            }
            else
            {
                var userEmail = HttpContext.User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
                orders = await orderService.GetUserOrder(userEmail, GetToken()); /// addd SearchString
            }

            return View(orders);
        }
        private string GetToken()
        {
            return HttpContext.Session.GetString(SD.SessionToken);
        }
    }
}

Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.Models;
using Web.Models.DTO.IdentityDTO;
using Web.Services.Interfaces;

namespace Web.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class UserController : Controller
    {
        private readonly IAdminService adminService;
        public UserController(IAdminService _adminService)
        {
            adminService = _adminService;
        }
        public async Task<IActionResult> Index(string? SearchString)
        {
            var Users = await adminService.GetAllUsers(SearchString, GetToken());

            return View(Users);
        }

        public async Task<IActionResult> Edit(string email)
        {
            var product = await adminService.GetUser(email, GetToken());

            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserWithRoleDTO user)
        {
            await adminService.ChangeRole(user, GetToken());

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string email)
        {
            var product = await adminService.GetUser(email, GetToken());

            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string email)
        {
            await adminService.DeleteUser(email, GetToken());

            return RedirectToAction("Index");
        }

        private string GetToken()
        {
            return HttpContext.Session.GetString(SD.SessionToken)!;
        }

    }
}

Web/Views/Shared/APIError.cshtml
@{
    ViewData["Title"] = "Error";
}

<h1 class="text-danger">API Error</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>


<h3>@ViewData["ErrorMessage"]</h3>
<p>
    Swapping to <strong>Development</strong> environment will display more detailed information about the error that occurred.
</p>
<p>
    <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
    It can result in displaying sensitive information from exceptions to end users.
    For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
    and restarting the app.
</p>

Web/Views/Shared/_CreateItem.cshtml
@model string;

@if (User.IsInRole("admin") || User.IsInRole("employee"))
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

Web/Views/Shared/_Identity.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
else
{

    @*User profile section*@
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello 
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Order" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>
            @if (User.IsInRole("admin"))
            {                
                <li>
                    <a class="dropdown-item" asp-controller="User" asp-action="Index">
                        <i class="bi bi-people"></i> Users
                    </a>
                </li>
            }            
        </ul>
    </div>
    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlayZone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">

    <!-- Include jQuery library -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Include Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Include Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Game" asp-action="Index">PlayZone</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        

                        @if (User.IsInRole("admin") || User.IsInRole("employee"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Management
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Game" asp-action="Index"><i class="bi bi-controller"></i>Games</a>
                                    <a class="dropdown-item" asp-controller="Producer" asp-action="Index"><i class="bi bi-headset"></i>Producers</a>
                                    <a class="dropdown-item" asp-controller="Category" asp-action="Index"><i class="bi bi-tags"></i>Categories</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Game" asp-action="Index"><i class="bi bi-controller"></i>Games</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Producer" asp-action="Index"><i class="bi bi-headset"></i>Producers</a>
                            </li>
                        }

                    </ul>
                    @{
                        string controllerName = this.ViewContext.RouteData.Values["controller"].ToString(); 
                    }

                    @await Html.PartialAsync("_Search", controllerName)


                    @*<ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>*@

                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GameStore
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/Views/Shared/_Search.cshtml
@model string;

@if(Model != "Account")
{
    <form class="form-inline my-2 my-lg-0" asp-controller="@Model" asp-action="Index" style="padding-right: 25px;">
        <input name="searchString" type="text" class="form-control" placeholder="Search for a @Model ..." aria-label="Recipient's username" aria-describedby="button-addon2">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
    </form>
}